### ISSUE TITLE
Culinarian solver quantity error

### ISSUE THREAD

**Issue by Neltisen** [CraftingAsAService/FFXIVCrafting#335]
Culinarian Slover for levels 35-36 list mats (and crafting amount) for a single craft of Cawl Cennin (resulting in 3 items), while Leve "Leak Soup for the Soul" require 9 items.

**Comment by Tickthokk** [comment]
So, the solver only exists to make one of each item. At early levels, the bonuses are enough to level you through, but that trend dies off. The solver is not intended to guarantee a level up, it's base theory is to just do everything once for the bonus once, then you'll need to level up through Leve/etc on your own. They're not connected.

If you need 9, you can add it through the recipe book!  http://ffxivcrafting.com/list/saved/4719,9

Thanks for the report though :)
