### ISSUE TITLE
Crafting recipes added to Crafting List from leves page don't add the required amount

### ISSUE THREAD

**Issue by Uriei** [CraftingAsAService/FFXIVCrafting#372]
When you add a recipe to the crafting list from the Leves List page, clicking on the cart icon it only adds 1 to the crafting list, but if you go into the leve info and add it from there, it adds the required amount for the leve.

From list:
![image](https://user-images.githubusercontent.com/6078221/147557716-de4deb0d-2f00-411f-95d9-88914c0d42e8.png)
![image](https://user-images.githubusercontent.com/6078221/147557721-a5bb0c99-067e-4705-a381-3375b0a3ad61.png)

From Leve info:
![image](https://user-images.githubusercontent.com/6078221/147557773-8227a596-7b4b-4718-96d6-a400e45da839.png)
![image](https://user-images.githubusercontent.com/6078221/147557827-0e0351e8-45aa-472d-8a8f-58dd31b98bdd.png)
![image](https://user-images.githubusercontent.com/6078221/147557838-4927db1c-7dda-43e9-b6f6-c9695f5be9fb.png)

Also seems to work fine from the Leve VS Leve page:
![image](https://user-images.githubusercontent.com/6078221/147557871-3599def8-8492-43fd-a361-f4b94572d27b.png)

**Comment by Tickthokk** [comment]
Thanks! This has been fixed and is live.
