### ISSUE TITLE
Search on recipes broken

### ISSUE THREAD

**Issue by manning390** [CraftingAsAService/FFXIVCrafting#374]
Typing in anything into the recipes search and clicking search appears to do nothing. Checking the console I see the following errors:

![image](https://user-images.githubusercontent.com/4450718/149649659-5803a9cb-37f9-47bf-967b-13fa4d181c69.png)

Payload:
```json
{"name":"partition","sort":"name.asc","levelMin":1,"levelMax":"900","stars":"any","jobs":{"Any":99},"page":1,"perpage":30}
```
Response:
![image](https://user-images.githubusercontent.com/4450718/149649689-9cc5f590-42c4-4b1e-866a-a957109145ce.png)

Os: Linux 5.15.7-arch1-1
Browser: Brave Version 1.32.113 Chromium: 96.0.4664.45 (Official Build) (64-bit)

**Comment by Tickthokk** [comment]
Hi! Thanks for the report. You've put in "900" as the max level, which causes it to error. That field is for equip level, not item level, however I could do more to prevent higher inputs from even getting in there.  For now you can just edit that down to 90 and it will work again.

---

- [ ] Put a max on the field

**Comment by manning390** [comment]
Yeah the UI toggle hides the third digit. Totally couldn't tell. Thanks!

**Comment by Tickthokk** [comment]
Permanent fix in an upcoming release. Better late than never ;) Thanks again for the report!
