### ISSUE TITLE
miscategorized Ore

### ISSUE THREAD

**Issue by Tickthokk** [CraftingAsAService/FFXIVCrafting#381]
New feedback from [jc.arisetioarmicit@gmail.com](mailto:jc.arisetioarmicit@gmail.com)
black limestone shows up as Origin: Other instead of something you mine

**Comment by and-rea** [comment]
Confirmed: It is (hidden) MIN quarrying in Quarterstone

**Comment by Tickthokk** [comment]
Fixed in upcoming release!
