### ISSUE TITLE
Alchemist Novice's Mortar shown during paging with craftable-only on

### ISSUE THREAD

**Issue by ashemedai** [CraftingAsAService/FFXIVCrafting#396]
Hi,

Alchemist equipment at level 29 and 30 show a Novice's Mortar, however, everything I found so far seems to indicate this is a levequest reward. Not something you can craft yourself. Rewards are not turned on (as per default). Checking on my blacksmith, I indeed only have an Initiate's Mortar (lv. 24), followed by a Steel Mortar (lv. 32).

**To reproduce**

1. Select Alchemist
2. Input level 25
3. Browse right by clicking the side bar of the display

Once you hit level 29 and 30 you see that suddenly the Novice's Mortar appears, despite "Only Craftable" being turned to YES at the bottom.

**Comment by Tickthokk** [comment]
Apologies! A response is well overdue :) I've fixed this bug and it'll be released soon. Your detailed report was very helpful. Thank you!

**Comment by ashemedai** [comment]
@Tickthokk Better late than never. Thanks for fixing it and having the website in the first place!
